dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
- rm local_settings.py
deploy:
  provider: heroku
  app: https://prueba-19.herokuapp.com/
  strategy: git
  api_key:
    secure: AqWhZR60YJs5nFuYcG7REFoNLkAD+MNwR6Pq4f+1WajNt4dfO9ef9OZ2BoSQ+pxOWrzwNMYt7oCT16ka+R+X7KAhMLTmMaDu020id488/6JCdyA3x9Tu/HtMTGLvZXmxIDHsolqBqdrIkC+MZ+dBQBdxgQka638x8ikUjADMrJOWj5LLwWNXWXzBjFalJd7s6FxrmXDxhLIJeU+L8QlLhc3J95a0R0JoKu0eMjTU/assVOyuWPENXbBehQHfPev6MGlbdvRFUQecHEbSpuNpl0cG4rdk6vC0rILt8XuJUKtelh1DaQGP4HqiILjGq/hMuP9mmuYCOEbxrH/7W3YNeFqOqF91jtu4XvXhzkGHRzlxOlHWj2bh4/7A4zgi+d6949yKxMRTyHl19uiribakVVcVlzR61LzGq0doMXLX21pJEl5KOr2R6TvLEnZ6hZZmpZF5V6ERW3ZQ5+33N3GOLy7OUd1Yw3Ez1K3mWtQAWadkJZV7cyKbsSM9bvGV55kp8IYL87/fZ9G4z1GcI8JiRsj18tq6Klu4O0F3OieCx3YkxJPj7y/UzGk30zRgX2rMXxHmh2rNIOiGMuyrTrKaiuhdMGaqK/XyHiMdpoXU3CNMICxHCS9+PPu66vPv8Qevpf53NrSNUbiX7qH4B2qtEhrVJUFCcYEu4/oT9cJAgTY=
